# Generated by Django 6.0.4 on 2026-07-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(default=False, editable=False, max_length=100, unique=True),
        ),
    ]
