# Generated by Django 6.0.4 on 2026-08-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_transaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
